name: mypy / mypyc

on:
  push:
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install mypy mypy-extensions pyyaml setuptools
      - name: mypy type check
        run: mypy --check-untyped-defs --namespace-packages bot bzflag
      - name: mypyc compilation check
        run: mypyc --namespace-packages bot bzflag
